
title: Code for Heilbronn e.V.
description: >-
  Offene Werkstatt - Open Data - Software- und Hardware Workshops

logo: /uploads/CodeForHeilbronn.svg
lang: de-DE
timezone: Europe/Berlin
permalink: /:year/:month/:day/:title.html
avatarurl: /favicon.png

markdown: kramdown

collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projekte
    output: true
  badges:
    title: Badges
    output: true
  events:
    title: Events
    output: true
  contributors:
    title: Mitwirkende
    output: true


navigation_header:
  Blog: /
  Verein: /verein
  Badges: /badges
  Projekte: /projects
  Termine: /events
  Wiki: https://github.com/opendata-heilbronn/Wiki/wiki
  Ãœber: /about

navigation_footer:
  Kategorien: /categories
  Satzung: /satzung
  Mitgliedsantrag: /uploads/Mitgliedsantrag.pdf

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
   - Gemfile
   - Gemfile.lock
   - .idea/
